### ISSUE TITLE
How does this plugin work?

### ISSUE THREAD

**Issue by pittar** [CycloneDX/cyclonedx-gradle-plugin#1]
Hi,

In the README, the instructions are "TODO", and in the code, I see a comment that says "This code does not currently work. TESTING ONLY".

I know very little about Gradle, so I can't help code this plugin, but if you can provide input on how to run it, I can help test.

Thanks.

**Comment by stevespringett** [comment]
I don't use Gradle and have only had one or two requests for it so far, so not a huge priority for me as of now. The plugin is not complete. Likely some more stuff will need to be ported from the Maven plugin and retrofit into the Gradle APIs in order to make is useful.

**Comment by pittar** [comment]
Thanks @stevespringett , that's very understandable.  I'm not sure how popular Gradle is these days, but there was a project I was helping out with a bit that was using it where I was hoping to create a BOM to upload to Dependency Track.

I'll keep an eye on this repo in case there is any movement just in case.  It might be easier to see if I can convince the devs to convert from Gradle to Maven.  Feel free to close this ticket if it makes sense to do so.

**Comment by matteoturra** [comment]
I think Gradle is quite popular. It is used in android project and springboot either.

**Comment by khamlaoui** [comment]
How could help to finish the development of this plugin? All our projects are using gradle and we want to use dependency track, but this is not possible without this plugin.
Thanks in advance

**Comment by stevespringett** [comment]
@khamlaoui The plugin is open source of PR are accepted. However, I'd highly suggest looking at the Maven plugin as most of the functionality needs to be ported over, and some of that work has started.

It would also be valuable to have both a single module project and complex multi-module project to test with.

**Comment by stevespringett** [comment]
@angrylogic contributed a PR which may provide some functionality - see #3 .  And although I've reviewed the code, I have no idea how to use it. Gradle is extremely frustrating and non-intuitive to me.

I checked in a test build script which we may be able to use for testing the plugin. And of course, I cannot get it to work nor have any idea on how to correct it.

Current snapshots of the plugin are deployed to OSSRH.

If someone can take a look and make the necessary corrections, I'd really appreciate it.

**Comment by matteoturra** [comment]
Sono fuori dall'ufficio fino a 14/06/2019




Nota: Questa è una risposta automatizzata al messaggio  "Re:
[CycloneDX/cyclonedx-gradle-plugin] How does this plugin work? (#1)"
inviata il 12/06/2019 06:45:00.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by stevespringett** [comment]
The plugin is being released. Usage is in the readme and there's a working example in the test directory.
