### ISSUE TITLE
Resolving configuration 'generatedImplementation' directly is not allowed

### ISSUE THREAD

**Issue by jamestweeddale** [CycloneDX/cyclonedx-gradle-plugin#10]
cyclonedxBom task runs but eventually fails with error "Resolving configuration 'generatedImplementation' directly is not allowed". Also seeing many "Unable to resolve POM for..." errors

> > Task :cyclonedxBom FAILED
> :cyclonedxBom (Thread[Daemon worker,5,main]) completed. Took 1 mins 58.585 secs.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':cyclonedxBom'.
> > Resolving configuration 'generatedImplementation' directly is not allowed
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 2m 5s
> 1 actionable task: 1 executed

**Comment by sschuberth** [comment]
@stevespringett, mind closing this, too, now that version 1.1.1 is released?
