### ISSUE TITLE
[information] configuration on build.gradle and dependencies

### ISSUE THREAD

**Issue by rios0rios0** [CycloneDX/cyclonedx-gradle-plugin#101]
Hello guys.

I have two doubts. Could you provide some assistance? Please.

I'm trying to use this plugin, and every configuration that I use, `Gradle` says to me that the property doesn't exist on task:
I'm doing only this configuration below:
```
cyclonedxBom {
    projectType = "application"
}
```
Gradle says to me that doesn't exist **projectType** on **cyclonedxBom**. How can I configure the task?

Second question:

I'm uploading the `bom.json/bom.xml` on [**Dependency Track**](https://dependencytrack.org/) and I can't see the dependency graph.
My `bom.xml` or `bom.json` doesn't have the "dependencies" entry. Where is the misconfiguration? 

![image](https://user-images.githubusercontent.com/32651906/135195046-24ba11ad-2ebc-44bd-9e13-41ad16db40a0.png)

Thanks in advance.

**Comment by stevespringett** [comment]
> I'm uploading the bom.json/bom.xml on Dependency Track and I can't see the dependency graph.
My bom.xml or bom.json doesn't have the "dependencies" entry. Where is the misconfiguration?

I don't think the gradle plugin supports dependency graph functionality yet.

`projectType` was introduced in v1.2.0 of the plugin. Ensure you're using v1.2.0 or higher.

**Comment by rios0rios0** [comment]
> > I'm uploading the bom.json/bom.xml on Dependency Track and I can't see the dependency graph.
> > My bom.xml or bom.json doesn't have the "dependencies" entry. Where is the misconfiguration?
> 
> I don't think the gradle plugin supports dependency graph functionality yet.
> 
> `projectType` was introduced in v1.2.0 of the plugin. Ensure you're using v1.2.0 or higher.

Hello, thanks for the answer. Yes, I'm using the latest 1.4.0.

**Comment by MagnusHaglund** [comment]
It would be great if the Gradle plugin supported dependency graph. It is nice to have in Dependency Track.
It looks like the Maven plugin supports it?

**Comment by officerNordberg** [comment]
> I'm trying to use this plugin, and every configuration that I use, `Gradle` says to me that the property doesn't exist on task: I'm doing only this configuration below:
> 
> ```
> cyclonedxBom {
>     projectType = "application"
> }
> ```
> 
> Gradle says to me that doesn't exist **projectType** on **cyclonedxBom**. How can I configure the task?
> 
I'm having the same issue on 1.5.0. The only way to get projectType set is via -PprojectType which is inconvenient for a multi-artifact project.   The code indicates it's only set via a Parameter.  

I have similar problems setting anything inside cyclonedxBom {} block, like trying to set tool metadata for vendor etc. to not display property placeholders

**Comment by unsaved** [comment]
Same here, but it also happens for version 1.4.0 from Maven Central.  For a sanity check I tried making a setting listed in the README.md file:

```
cyclonedxBom {
    schemaVersion = '1.2'
}
```

This generates: 
```
> Could not set unknown property 'schemaVersion' for task ':cyclonedxBom' of type org.cyclonedx.gradle.CycloneDxTask.
```

**Comment by msymons** [comment]
Adding my vote for adding support for dependencies to the plugin.  

I have users who are crying out for this, saying that (thanks to analyis of the BOM) they know they have a vulnerability to address.. but have trouble working out how the vulnerable component is getting into the project.

I tried using `htmlDependencyReport` and publishing the results in Jenkins.  Ughh.  Sucks.
