### ISSUE TITLE
Convert SCM SSH URL's to HTTPS

### ISSUE THREAD

**Issue by spliffone** [CycloneDX/cyclonedx-gradle-plugin#123]
# Problem

The maven projects (pom files) sometimes contain SCM URL's as GIT SSH connect strings. Since they aren't valid URL this information get lost during the process (see also https://github.com/CycloneDX/specification/issues/141).

Sample syntax for POM SCM URL's:
- scm:git:git@github.com:user/repo.git
- scm:git:git://github.com/user/repo.git
- git@github.com:user/repo.git

Samples:
- https://repo1.maven.org/maven2/com/jayway/jsonpath/json-path/2.7.0/json-path-2.7.0.pom
- https://repo1.maven.org/maven2/com/zaxxer/HikariCP/5.0.1/HikariCP-5.0.1.pom
- https://repo1.maven.org/maven2/com/zaxxer/SparseBitSet/1.2/SparseBitSet-1.2.pom
- https://repo1.maven.org/maven2/io/micrometer/micrometer-core/1.8.5/micrometer-core-1.8.5.pom

# Proposal

Convert the SCM URL to a valid HTTPS URL before the plugin calls `addExternalReference`.
Rules:
- Remove `scm:git:` prefix
- Replace `git@` with `https://`
- Replace `git://` with `https://`
- Replace `:` with `/`

**Comment by jkowalleck** [comment]
get your github urls normalized. 

`git@github.com:aws/aws-sdk-js-crypto-helpers.git` shall be normalized to 
`git+https://github.com/aws/aws-sdk-js-crypto-helpers.git`

**Comment by jkowalleck** [comment]
Remember: 
each VCS hoster may have an own mapping. what works for github may not work for gitlab, and may not work four your on-prem custom solution.

**Comment by spliffone** [comment]
It is true it will not work for all VCS hoster but it was a approach to improve the existing restriction of the CycloneDX scheme. I will close the issue.
