### ISSUE TITLE
Provide plugin in Gradle Plugin Portal

### ISSUE THREAD

**Issue by stefanneuhaus** [CycloneDX/cyclonedx-gradle-plugin#13]
Having the plugin available in the [Gradle Plugin Portal](https://plugins.gradle.org/) allows for the applying the plugin using the [plugins DSL](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:using_your_plugin_in_another_project). If possible, this is often the preferred way.

If not required, having the plugin's build use Gradle is probably the most obvious way. This also comes with other benefits like support for easily testing the plugin during the build.

**Comment by stevespringett** [comment]
If there is a Maven way of adding the plugin to the plugin portal, this project accepts pull requests. However, the project will not be migrating from maven to gradle.

**Comment by sschuberth** [comment]
> However, the project will not be migrating from maven to gradle.

Hmm, while I respect your personal preference here, does that restriction really make sense from a technical perspective? To me, it feels more native to build a Gradle plugin with Gradle, and you could make use of helpers like the [Java Gradle Plugin Development Plugin](https://docs.gradle.org/current/userguide/java_gradle_plugin.html#java_gradle_plugin).

**Comment by stevespringett** [comment]
I agree, however, this project doesn't have a maintainer that knows Gradle. If that changes in the future, I have no objection, but if the maintainer is going to continue to be myself, I need something I know how to maintain (which is not Gradle).

**Comment by llamahunter** [comment]
would you be open to having a separate gradle build that does the portal publishing?

**Comment by stevespringett** [comment]
Certainly, as long as it's independent. I'll likely need docs on how to execute the build

**Comment by llamahunter** [comment]
see https://github.com/CycloneDX/cyclonedx-gradle-plugin/pull/36

**Comment by llamahunter** [comment]
With the merge of #36, will there be an upcoming publishing of the plugin to the Gradle Plugin Portal?  New version, or 1.1.1?

**Comment by llamahunter** [comment]
When will the plugin get published to the gradle plugin portal?

**Comment by stevespringett** [comment]
Its been published, but it doesn't seem to be automated. Received the following after a successful publish:

> Publishing plugin org.cyclonedx.bom version 1.1.2
> Thank you. Your new plugin org.cyclonedx.bom has been submitted for approval by Gradle engineers. The request should be processed within the next 24 hours, at which point you will be contacted via email.

Hopefully this is a one-time thing and not for every update.

**Comment by llamahunter** [comment]
I think I covered that in the document.  It's a one time thing to approve 'ownership' of the plugin's namespace. 

> If this is the first time the plugin has been published, the name may need to be approved by the portal maintainers. This typically takes about 12 hours during the work week. You will see on your portal user console page that your plugin is marked 'Pending approval'. After it is approved, the API credentials used to publish will 'own' the plugin name, and plugins will be available in the portal immediately after publishing.

**Comment by stevespringett** [comment]
Thanks @llamahunter for all the info and quality PR.

https://plugins.gradle.org/plugin/org.cyclonedx.bom
