### ISSUE TITLE
Problem with encoding utf-8

### ISSUE THREAD

**Issue by BartoszCoyote** [CycloneDX/cyclonedx-gradle-plugin#139]
I got error
`18:07:59  An error occurred attempting to read POM
18:07:59  org.codehaus.plexus.util.xml.pull.XmlPullParserException: UTF-8 BOM plus xml decl of iso-8859-1 is incompatible (position: START_DOCUMENT seen <?xml version="1.0" encoding="iso-8859-1"... @1:41) `

I get this error for the dozen or so libraries I scan

**Comment by stevespringett** [comment]
Related to https://github.com/CycloneDX/cyclonedx-maven-plugin/issues/117
