### ISSUE TITLE
cyclonedxBom task should have a task group assigned

### ISSUE THREAD

**Issue by sschuberth** [CycloneDX/cyclonedx-gradle-plugin#14]
Otherwise `./gradlew tasks` [does not list the task](https://stackoverflow.com/a/23598928/1127485), only `./gradlew tasks --all` does (and then currently in the "Other tasks" group).

**Comment by matteoturra** [comment]
Sono fuori dall'ufficio fino a 09/09/2019




Nota: Questa è una risposta automatizzata al messaggio
"[CycloneDX/cyclonedx-gradle-plugin] cyclonedxBom task should have a task
group assigned (#14)" inviata il 02/09/2019 17:50:54.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by stevespringett** [comment]
I honestly don't know what this means. I typically stay away from Gradle, so if you can recommend a change, that would be ideal.

**Comment by matteoturra** [comment]
Sono fuori dall'ufficio fino a 09/09/2019




Nota: Questa è una risposta automatizzata al messaggio  "Re:
[CycloneDX/cyclonedx-gradle-plugin] cyclonedxBom task should have a task
group assigned (#14)" inviata il 03/09/2019 03:43:18.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by sschuberth** [comment]
> I typically stay away from Gradle

Heh, just like me staying away from Maven nowadays if I can :wink: But I'll try to find the time for a PR.
