### ISSUE TITLE
Some listed dependencies not in the project

### ISSUE THREAD

**Issue by slowcar** [CycloneDX/cyclonedx-gradle-plugin#165]
We used cyclonedx to analyze our dependencies, the analysis shows a few libraries with outdated versions etc:

![bom analysis](https://user-images.githubusercontent.com/28760605/171595695-2dbbcde5-e56d-4f72-bf00-c3afadcb78d4.png)

However, the listed libraries are either not used in the project, or are used in newer versions.
I used "gradle dependencies" to create a dependency tree, and can't find these:

- commons-compress
- bcprov-jdk15on
- protobuf-java
- xerces

commons-compress is found in the Android sdk tools directory and seems to be part of the gradle wrapper distribution, but those are only used to build the project and don't become part of it.
I have decompiled our apk, but found no trace of these libraries, and know of no library that we use which has it as a dependency.

these are used as dependecies, but listed with both the new and old versions in the bom, which may be a different issue:

- httpclient (outputs 4.5.6, actually uses 4.5.8)
- gson  (outputs 2.8.6, actually uses 2.9.0)
- guava (outputs 28.1.-jre, uses 31.1-jre)

for example, we use com.microsoft.identity:common:4.0.2, which has this entry in the gradle dependency output:
+--- com.google.code.gson:gson:2.8.5 -> 2.9.0

gradle automatically uses the newer version, as indicated by the "->"

**Comment by glefloch** [comment]
Thanks for reporting this @slowcar. I will have a look.

**Comment by SneerAzrael** [comment]
it was in lintClassPath , you  can ignore it !

**Comment by glefloch** [comment]
Great thanks, I will close the issue then
