### ISSUE TITLE
Exclude test dependencies

### ISSUE THREAD

**Issue by rstmm** [CycloneDX/cyclonedx-gradle-plugin#166]
Is there an option to exclude test dependencies? Sorry I couldn't find it in the docs
for example here:
```
dependencies {
   implementation group: 'org.greenrobot', name: 'eventbus-java', version: '3.3.1'
   testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.8.2'
}
```

**Comment by msymons** [comment]
I dealt with this exactly this problem a couple of years ago by using `skipconfigs`.   That led me to log #68,  which was implemented, so you can now also use `includeConfigs` as an alternative approach.

**Comment by glefloch** [comment]
Right, by default all configurations are scan, but as @msymons mentioned it, you can exclude configurations using `skipConfigs` are if you only want specific to be scan, you can use `includeConfigs`

**Comment by rstmm** [comment]
Thank you. We tried skipConfigs, but somehow it showed the same result. Working with includeConfigs limiting to only implementation classpath works well now.
