### ISSUE TITLE
cyclonedx-gradle-plugin no longer published on https://plugins.gradle.org/m2/

### ISSUE THREAD

**Issue by dietzsch** [CycloneDX/cyclonedx-gradle-plugin#183]
Since version 1.5.0 of cyclonedx-gradle-plugin the plugin binaries are no longer published on https://plugins.gradle.org/m2/. Is there something wrong with the publish as in the publish action I can see for version 1.7.0 that the build scan mentions NOT PUBLISHED. 
Or has the publish location changed and the documentation at https://plugins.gradle.org/plugin/org.cyclonedx.bom is just incorrect?

best regards
Alex

**Comment by ChristianCiach** [comment]
At some point the org has been changed from `com.*` to `org.`. See:

https://plugins.gradle.org/m2/org/cyclonedx/cyclonedx-gradle-plugin/

vs 

https://plugins.gradle.org/m2/com/cyclonedx/cyclonedx-gradle-plugin/

**Comment by dietzsch** [comment]
Thank you for clarification. Missed this chnage.
