### ISSUE TITLE
support version property

### ISSUE THREAD

**Issue by pjfanning** [CycloneDX/cyclonedx-gradle-plugin#191]
The cyclonedx properties - it would be useful if the 'version' that appears in the generated was configurable. (cf Configuration section in README).

For instance, for POMs, gradle supports:

```
publishing {
    publications {
        POI(MavenPublication) {
            groupId 'org.apache.poi'
            artifactId project.archivesBaseName
            version XMLBeansVersion
            ...
```

**Comment by glefloch** [comment]
The version used in the sbom comes from the `version` properties of your project. Could you explain a bit more why we should be able to override this version in the plugin ? 
If I understand correctly, we could end up with the following configuration in the `build.gradle`file right ?
````
plugins {
...
}
version = '1.1.1'

cyclonedxBom {
   componentVersion = '2.0.0'
}
````

**Comment by pjfanning** [comment]
@glefloch thanks for looking at this.

In https://github.com/apache/xmlbeans, the project version is not used because some packaging code ends up appending version number in wrong place in the name of the generated artifacts. A custom property is used instead.

You suggestion about an optional cyclonedxBom  `componentVersion` would work in my use case.

**Comment by glefloch** [comment]
Ok, I will add that property as part of plugin configuration
