### ISSUE TITLE
"The BOM does not conform to the CycloneDX BOM standard" for root projects in 1.7.0

### ISSUE THREAD

**Issue by evan-vanderhoeven** [CycloneDX/cyclonedx-gradle-plugin#194]
I'm adding this gradle plugin to a Kotlin project for the first time and when trying to generate the BOM I get the following error message:
```
CycloneDX: Creating BOM
CycloneDX: Writing BOM XML
CycloneDX: Validating BOM

> Task :cyclonedxBom FAILED
:cyclonedxBom (Thread[Execution worker for ':',5,main]) completed. Took 9.571 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cyclonedxBom'.
> The BOM does not conform to the CycloneDX BOM standard

```

After some experimentation with a hello world project, it works when added to a subproject build script in the same project. Both Kotlin and Groovy scripts get the same result. But reverting to 1.6.1 works for me so I think it's a bug in the most recent version. Just to be clear I have `build.gradle.kts` in the root directory of my application.

build.gradle.kts (just the relevant bits):
```
plugins {
    id("org.cyclonedx.bom") version "1.7.0" // 1.6.1 works for me
}

tasks.cyclonedxBom {
        setIncludeConfigs(listOf("runtimeClasspath"))
        setSkipConfigs(listOf("compileClasspath", "testCompileClasspath"))
        setProjectType("application")
        setSchemaVersion("1.4")
    }
```

**Comment by dietzsch** [comment]
Actually I'm facing the same issue with a multi-module Gradle project where the BOM is generated with both versions of the plugin, but with the new version of the plugin the validation fails with non concrete error. From the generated XML/JSON files I can not see an obvious failure that cause the validation issue.

**Comment by SaberStrat** [comment]
Same here with a multi-project. Didn't have that issue with prior versions.

**Comment by glefloch** [comment]
Thanks for reporting this issue, I will have a look ASAP. 
Are you all working on kotlin based project?

**Comment by dietzsch** [comment]
Hi @glefloch, we are using Java in our projects.

**Comment by MagnusHaglund** [comment]
Hi we have this issue too with a multi-module Gradle project - using Java. It works with version 1.6.1 but not with 1.7.0.
It does produce a bom.xml file despite the error, but no json file.

When uploading the bom.xml manually to Dependency Track, no Dependency Graph i shown though, which we lacked in the previous version and we hoped 1.7.0 would fix.

**Comment by SaberStrat** [comment]
Java here too

**Comment by tcdev00** [comment]
I have the same issue when running `1.7.1`. Like @evan-vanderhoeven , I confirm that `1.6.1` works.

**Comment by aledeulo** [comment]
Hi there, I have a multi-project structure too, with gradle. I'm using the cycloneDx version 1.7.4 and I'm facing the very same issue. Any workaround here? 

`
CycloneDX: Creating BOM
CycloneDX: Writing BOM JSON
CycloneDX: Validating BOM

> Task :cyclonedxBom FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':cyclonedxBom'.
> The BOM does not conform to the CycloneDX BOM standard

`
