### ISSUE TITLE
1.7.1 does not work, if cyclonedx is used in subproject

### ISSUE THREAD

**Issue by Dalamaar** [CycloneDX/cyclonedx-gradle-plugin#209]
Our Gradle-multi-project build is structured in a way, so that there are two separate artifacts, that are released. (Server and client) These are each subprojects side-by-side to other subprojects. The cyclonedx-plugin is included in the two subprojects and is also called inside of them (:server:cyclonedxBom and :client:cyclonedxBom).

In 1.7.0 the creation worked just fine, but in 1.7.1 the plugin tries to collect the dependencies of the whole project and not only of the subprojects. This fails with "The BOM does not conform to the CycloneDX BOM standard" and the resulting bom.json differs significantly to the one in 1.7.0.

A look at the changes in 1.7.1 make it obvious, that the dependency-collection now always starts at root level, which must not happen in our case. Can it be changed again, so that the project, from which it was called, counts as the root?

Gradle version is 7.5.1.

Project structure:
```
root
    server
    client
    other subproject 1
    other subproject 2
    ...
```
The root project does not depend on either of the subprojects. Server and client depend on the other subprojects, but not on each other.

Plugin config in server and client build.gradle:
```
plugins {
    [...]
    id 'org.cyclonedx.bom' version '1.7.1'
}

cyclonedxBom {
    includeConfigs = ["runtimeClasspath"]
    projectType = "application"
    outputFormat = "json"
}
```

**Comment by lislei** [comment]
I can confirm the same issue with a similar configuration running on Gradle 6.9.

**Comment by glefloch** [comment]
Thanks for reporting it @Dalamaar, I will have a look at it. Do you have a simple reproducer project?

**Comment by Dalamaar** [comment]
I could recreate the problem with a basic gradle project, see https://github.com/Dalamaar/cyclonedx-test. CycloneDx is included in the app subproject.

**Comment by glefloch** [comment]
Thanks

**Comment by tillkuhn** [comment]
I can confirm the same issue with a similar configuration running on Gradle 7.5.1 / Java 17.0.4.1! Plugin Version `1.7.1` fails with exception, Version `1.7.0` works, gradle is launched from the subpath. Thanks!

**Comment by mikethecalamity** [comment]
@glefloch 

I'm still seeing this with `1.7.2` if I run: `gradlew myproject:cyclonedxBom`

JDK 17.0.2
Gradle 7.4.2
Quarkus 2.13.4

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myproject:cyclonedxBom'.
Caused by: org.gradle.api.GradleException: The BOM does not conform to the CycloneDX BOM standard
        at org.cyclonedx.gradle.CycloneDxTask.writeXMLBom(CycloneDxTask.java:583)
        at org.cyclonedx.gradle.CycloneDxTask.writeBom(CycloneDxTask.java:557)
        at org.cyclonedx.gradle.CycloneDxTask.createBom(CycloneDxTask.java:305)
Caused by: org.gradle.api.GradleException: The BOM does not conform to the CycloneDX BOM standard
        at org.cyclonedx.gradle.CycloneDxTask.writeXMLBom(CycloneDxTask.java:579)
        ... 121 more
```
