### ISSUE TITLE
Dependency graph not working

### ISSUE THREAD

**Issue by 2013kaa** [CycloneDX/cyclonedx-gradle-plugin#224]
Hi, my bom.json does not contain the "dependsON" attribute.
I'm using cyclonDx as a gradle plugin.
The complete command looks like this:
./gradlew --no-daemon --init-script cyclondx_init.gradle cyclonedxBom -info

cyclondx_init.gradle is an init script that adds the com.cyclonedx:cyclonedx-gradle-plugin:1.7.2  plugin to gradle

Tell me what could be the problem?

**Comment by glefloch** [comment]
Could you share a sample project and the output?

**Comment by 2013kaa** [comment]
@glefloch

**Comment by 2013kaa** [comment]
@glefloch 
I understood what was my mistake (I got confused in the project branches).
But now there is a slightly different problem, I added the gradle plugin version 1.7.2 and I get an error:

> Could not resolve all artifacts for configuration ':classpath'.
    > Could not find com.cyclonedx:cyclonedx-gradle-plugin:1.7.2.
      Searched in the following locations:
        - https://repo.maven.apache.org/maven2/com/cyclonedx/cyclonedx-gradle-plugin/1.7.2/cyclonedx-gradle-plugin-1.7.2.pom
        - https://plugins.gradle.org/m2/com/cyclonedx/cyclonedx-gradle-plugin/1.7.2/cyclonedx-gradle-plugin-1.7.2.pom


Indeed, there is no such version in the repository.
![image](https://user-images.githubusercontent.com/46608135/197202105-e7b46868-e446-4fe3-aa94-8c7e69325a3b.png)
Tell me how to be?

**Comment by stevespringett** [comment]
I believe all the com.cyclonedx was published in error and that org.cyclonedx is now correctly used.

**Comment by 2013kaa** [comment]
It seems like they solved the issue and added it. Thank you!
