### ISSUE TITLE
A component's dependencies are lost if it's depended on by multiple components

### ISSUE THREAD

**Issue by Trample03** [CycloneDX/cyclonedx-gradle-plugin#230]
Hi team,
<br/>

I noticed that there is a bug in [CycloneDxTask.buildDependencyGraph](https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/6e9ad2892a121ff08c775f0191284fe88e428ffd/src/main/java/org/cyclonedx/gradle/CycloneDxTask.java#L320).
```java
private Map<String, org.cyclonedx.model.Dependency> buildDependencyGraph(Map<String, org.cyclonedx.model.Dependency> dependenciesSoFar, ResolvedDependency resolvedDependency, ResolvedArtifact jarArtifact) {
    String dependencyPurl = generatePackageUrl(jarArtifact);
    org.cyclonedx.model.Dependency dependency = new org.cyclonedx.model.Dependency(dependencyPurl);
    if (dependenciesSoFar.put(dependencyPurl, dependency) != null){  // NOTICE HERE
        return dependenciesSoFar;
    }
    for (ResolvedDependency childDependency : resolvedDependency.getChildren()) {
        ResolvedArtifact childJarArtifact = getJarArtifact(childDependency);
        if (childJarArtifact != null) {
            dependency.addDependency(new org.cyclonedx.model.Dependency(generatePackageUrl(childJarArtifact)));
            buildDependencyGraph(dependenciesSoFar, childDependency, childJarArtifact);
        }
    }
    return dependenciesSoFar;
}
```
if the map `dependenciesSoFar` already contains the key `dependencyPurl`, `dependenciesSoFar.put()` will replace the old value with the new one which has no dependencies. And then it returns immediately so the dependencies of the new `org.cyclonedx.model.Dependency` object in the map will never be updated.
<br/>

This can be easily reproduced by a project with dependencies as follows since the two components all depends on `io.quarkus:quarkus-jackson`:
```gradle
dependencies {
    implementation("io.quarkus:quarkus-resteasy-jackson")
    implementation("io.quarkus:quarkus-rest-client-jackson")
}
```
<br/>

And it can be fixed just like this:
```java
    if (dependenciesSoFar.containsKey(dependencyPurl)){
        return dependenciesSoFar;
    }
    dependenciesSoFar.put(dependencyPurl, dependency);
```
<br/>

Hope this can help you.
<br/>

Regards

**Comment by glefloch** [comment]
Nice catch ! I will push a fix. Thanks !
