### ISSUE TITLE
Can aar types be supported ？

### ISSUE THREAD

**Issue by xiang123abc** [CycloneDX/cyclonedx-gradle-plugin#234]
> Can  **aar**  types be supported ? 

such as:
``
dependencies {
implementation group :'me. relex', name :'circleindicator', version :'2.1.6'
}
``
**me. relex:circleindicator:2.1.6**    type is   aar  , 
https://repo1.maven.org/maven2/me/relex/circleindicator/2.1.6/circleindicator-2.1.6.pom

now ,if use aar type ,  bom.json has not dependencies

thanks!

**Comment by skhokhlov** [comment]
#532 featured new implementation of dependency resolution which supports artifacts of any types.
