### ISSUE TITLE
Execution failed for task ':automotive:cyclonedxBom'

### ISSUE THREAD

**Issue by chetan-ansel** [CycloneDX/cyclonedx-gradle-plugin#259]
I have tried cyclonedxBom in an android project with the Gradle version  
**classpath 'com.android.tools.build:gradle:7.0.2'**
and kotlin version   
**classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20"** 

cycloneDxBom: plugins {
    id 'org.cyclonedx.bom' version '1.7.3'
}
apply plugin: 'org.cyclonedx.bom'

and every time Build failed with an exception.

Execution failed for task ':automotive:cyclonedxBom'.
> The consumer was configured to find a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :automotive:
    - Configuration ':automotive:releaseRuntimeElements' variant android-base-module-lint-variant-dependencies-model declares a runtime of a component, preferably optimized for Android
, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
        - Unmatched attributes:
            - Provides attribute 'artifactType' with value 'android-base-module-lint-variant-dependencies-model' but the consumer didn't ask for it
            - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
            - Provides a library but the consumer didn't ask for it
    - Configuration ':automotive:releaseRuntimeElements' variant android-java-res declares a runtime of a component, preferably optimized for Android, as well as attribute 'com.android
.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value '**androidJvm**':
        - Unmatched attributes:
            - Provides attribute 'artifactType' with value 'android-java-res' but the consumer didn't ask for it
            - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
            - Provides a library but the consumer didn't ask for it
    - Configuration ':automotive:releaseRuntimeElements' variant android-lint-variant-dependencies-model declares a runtime of a component, preferably optimized for Android, as well as
 attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
        - Unmatched attributes:
            - Provides attribute 'artifactType' with value 'android-lint-variant-dependencies-model' but the consumer didn't ask for it
            - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
            - Provides a library but the consumer didn't ask for it
    - Configuration ':automotive:releaseRuntimeElements' variant android-navigation-json declares a runtime of a component, preferably optimized for Android, as well as attribute 'com.
android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
        - Unmatched attributes:
            - Provides attribute 'artifactType' with value 'android-navigation-json' but the consumer didn't ask for it
            - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
            - Provides a library but the consumer didn't ask for it
    - Configuration ':automotive:releaseRuntimeElements' variant android-packaged-dependencies declares a runtime of a component, preferably optimized for Android, as well as attribute
 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
        - Unmatched attributes:
            - Provides attribute 'artifactType' with value 'android-packaged-dependencies' but the consumer didn't ask for it
            - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
            - Provides a library but the consumer didn't ask for it
    - Configuration ':automotive:releaseRuntimeElements' variant apk declares a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.at
tributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
        - Unmatched attributes:
            - Provides attribute 'artifactType' with value 'apk' but the consumer didn't ask for it
            - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
            - Provides a library but the consumer didn't ask for it
    - Configuration ':automotive:releaseRuntimeElements' variant bundle-apks declares a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.buil
d.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
        - Unmatched attributes:
            - Provides attribute 'artifactType' with value 'bundle-apks' but the consumer didn't ask for it
            - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
            - Provides a library but the consumer didn't ask for it

**Note: When I lowered the version of Gradle to 3.6.4( classpath 'com.android.tools.build:gradle:3.6.4') and build executed successfully and cycloneDx was able to generate reports files(bom.json and bom.xml)**

**Comment by chetan-ansel** [comment]
It got works when I added configuration: 
**cyclonedxBom {
    skipConfigs = [
            "debugCompileClasspath",
            "debugAndroidTestCompileClasspath",
            "debugUnitTestCompileClasspath",
            "releaseUnitTestCompileClasspath",
            "debugUnitTestRuntimeClasspath",
            "releaseUnitTestRuntimeClasspath"
    ]
}**

**But when I tried on another project with flavor it got failed( 
**productFlavors** {
        nonprod {
            dimension AppLevelDependencies.AppConfig.appDimension
            applicationId AppLevelDependencies.AppConfig.qaApplicationId
        }
        prod {
            dimension AppLevelDependencies.AppConfig.appDimension
            applicationId AppLevelDependencies.AppConfig.prodApplicationId
  
        }
    }

    **sourceSets** {
        prod {
            res { 'src/prod/res' }
        }
        nonprod {
            res { 'src/nonprod/res' }
        }
    }. ]Below is the error:**  
The consumer was configured to find a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:environment' with value 'prod', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.1.0', attribute 
'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :automotive:
    - Configuration ':automotive:prodDebugRuntimeElements' variant android-base-module-lint-variant-dependencies-model declares a runtime of a component, preferably optimized for Andro
id, as well as attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.1.0', attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 
'com.android.build.api.attributes.ProductFlavor:environment' with value 'prod', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
        - Unmatched attributes:
            - Provides attribute 'artifactType' with value 'android-base-module-lint-variant-dependencies-model' but the consumer didn't ask for it
            - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'prodDebug' but the consumer didn't ask for it
            - Provides attribute 'environment' with value 'prod' but the consumer didn't ask for it
            - Provides a library but the consumer didn't ask for it
    - Configuration ':automotive:prodDebugRuntimeElements' variant android-java-res declares a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.1.0', attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.P
roductFlavor:environment' with value 'prod', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
        - Unmatched attributes:
            - Provides attribute 'artifactType' with value 'android-java-res' but the consumer didn't ask for it
            - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'prodDebug' but the consumer didn't ask for it
            - Provides attribute 'environment' with value 'prod' but the consumer didn't ask for it
            - Provides a library but the consumer didn't ask for it
    - Configuration ':automotive:prodDebugRuntimeElements' variant android-lint-variant-dependencies-model declares a runtime of a component, preferably optimized for Android, as well 
as attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.1.0', attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android
.build.api.attributes.ProductFlavor:environment' with value 'prod', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
        - Unmatched attributes:
            - Provides attribute 'artifactType' with value 'android-lint-variant-dependencies-model' but the consumer didn't ask for it
            - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'prodDebug' but the consumer didn't ask for it
            - Provides attribute 'environment' with value 'prod' but the consumer didn't ask for it
            - Provides a library but the consumer didn't ask for it
    - Configuration ':automotive:prodDebugRuntimeElements' variant android-navigation-json declares a runtime of a component, preferably optimized for Android, as well as attribute 'co
m.android.build.api.attributes.AgpVersionAttr' with value '7.1.0', attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attri
butes.ProductFlavor:environment' with value 'prod', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
        - Unmatched attributes:
            - Provides attribute 'artifactType' with value 'android-navigation-json' but the consumer didn't ask for it
            - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'prodDebug' but the consumer didn't ask for it
            - Provides attribute 'environment' with value 'prod' but the consumer didn't ask for it
            - Provides a library but the consumer didn't ask for it
    - Configuration ':automotive:prodDebugRuntimeElements' variant android-packaged-dependencies declares a runtime of a component, preferably optimized for Android, as well as attribu
te 'com.android.build.api.attributes.AgpVersionAttr' with value '7.1.0', attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api
.attributes.ProductFlavor:environment' with value 'prod', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
        - Unmatched attributes:
            - Provides attribute 'artifactType' with value 'android-packaged-dependencies' but the consumer didn't ask for it
            - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'prodDebug' but the consumer didn't ask for it
            - Provides attribute 'environment' with value 'prod' but the consumer didn't ask for it
            - Provides a library but the consumer didn't ask for it
    - Configuration ':automotive:prodDebugRuntimeElements' variant apk declares a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.
attributes.AgpVersionAttr' with value '7.1.0', attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:
environment' with value 'prod', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
        - Unmatched attributes:
            - Provides attribute 'artifactType' with value 'apk' but the consumer didn't ask for it
            - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'prodDebug' but the consumer didn't ask for it
            - Provides attribute 'environment' with value 'prod' but the consumer didn't ask for it
            - Provides a library but the consumer didn't ask for it
    - Configuration ':automotive:prodDebugRuntimeElements' variant bundle-apks declares a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.bu
ild.api.attributes.AgpVersionAttr' with value '7.1.0', attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.Produc
tFlavor:environment' with value 'prod', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
        - Unmatched attributes:
            - Provides attribute 'artifactType' with value 'bundle-apks' but the consumer didn't ask for it
            - Provides attribute 'com.android.build.gradle.internal.attributes.VariantAttr' with value 'prodDebug' but the consumer didn't ask for it
            - Provides attribute 'environment' with value 'prod' but the consumer didn't ask for it
            - Provides a library but the consumer didn't ask for it


**Note: if I commented out the product flavors and source sets in the build.gradle CycloneDX is able to generate the output file.**

**Comment by chetan-ansel** [comment]
I am able to fix this issue by skipping config for flavors like:
cyclonedxBom {
    skipConfigs = [
            "debugCompileClasspath",
            "debugAndroidTestCompileClasspath",
            "debugUnitTestCompileClasspath",
            "debugUnitTestRuntimeClasspath",
      "releaseUnitTestCompileClasspath",
            "releaseUnitTestRuntimeClasspath",
            **"nonprodDebugCompileClasspath",
            "nonprodDebugAndroidTestCompileClasspath",
            "nonprodDebugUnitTestCompileClasspath",
            "nonprodDebugUnitTestRuntimeClasspath",**
            **"prodDebugCompileClasspath",
            "prodDebugAndroidTestCompileClasspath",
            "prodDebugUnitTestCompileClasspath",
            "prodDebugUnitTestRuntimeClasspath",**
            **"prodReleaseUnitTestCompileClasspath",
            "prodReleaseUnitTestRuntimeClasspath",
            "nonprodReleaseUnitTestCompileClasspath",
            "nonprodReleaseUnitTestRuntimeClasspath"**
    ]
    outputName = "bom"
    // The file format generated, can be xml, json or all for generating both
    outputFormat = "json"
} I hope have it might help others

**Comment by skhokhlov** [comment]
Main issue: https://github.com/CycloneDX/cyclonedx-gradle-plugin/issues/478
