### ISSUE TITLE
Facilitate DCO in GitHub web UI

### ISSUE THREAD

**Issue by Bert-R** [CycloneDX/cyclonedx-gradle-plugin#275]
Given that DCO is mandatory, you might want to enable check the box "Require contributors to sign off on web-based commits"  on this repo, as described here: https://github.com/todogroup/gh-issues/issues/50#issuecomment-1148657762

That prevents an issue like I just ran into: #274

**Comment by glefloch** [comment]
I don't have access to all repository configuration, maybe @stevespringett could you have a look ?

**Comment by stevespringett** [comment]
Ok. it should be enabled now. My Internet is spotty atm, so it the config didn't take, ping another person on the core team.

**Comment by Bert-R** [comment]
It works properly, see #317.

**Comment by glefloch** [comment]
Great ! Thanks @stevespringett.
