### ISSUE TITLE
SPDX support?

### ISSUE THREAD

**Issue by mathjeff** [CycloneDX/cyclonedx-gradle-plugin#276]
We've been asked to make SPDX SBOM files for our Gradle build, and we notice the cyclonedx-gradle-plugin looks pretty nice, writing a nonempty file that looks like an SBOM, even without any extra configuration.

It seems to me that it would be nice for an spdx-generating solution to reuse the data model from this plugin, and could potentially result in less duplicate code if it's part of this plugin.

I see that this GitHub project is tagged as "spdx" but I don't notice any tasks for generating spdx files, only tasks for generating CycloneDX files ( `cyclonedxBom` ).

Is it possible to generate spdx files with this plugin (or a similar one)? Is that something that could be interesting to have on the roadmap?

Thanks

**Comment by stevespringett** [comment]
CycloneDX supports SPDX license IDs and expressions. CycloneDX and SPDX vary dramatically on file formats and compete in this area. Your best bet would be to convert CycloneDX to legacy SPDX format using the CycloneDX CLI.

**Comment by glefloch** [comment]
Closing this as no development is required
