### ISSUE TITLE
Artifact name not resolved correctly when "archivesBaseName" is changed

### ISSUE THREAD

**Issue by bflood-agi** [CycloneDX/cyclonedx-gradle-plugin#298]
Hi all,

After running `cyclonedxBom` and inspecting the output, I noticed that our first-party artifacts were incorrectly named. In our project, we prefix JARs with the root project's name like this:

```groovy
archivesBaseName = "${rootProject.name}-${name}"
```

This should result in a `purl` like `pkg:maven/com.example/myproject-utilities@1.0.0-SNAPSHOT?type=jar`. Instead, I'm seeing `pkg:maven/com.example/utilities@1.0.0-SNAPSHOT?type=jar`.

I believe this is caused by the way artifact names are resolved in [DependencyUtils](https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/12a5de0bd48b1de3946ace2fc8c1694ab3f38f58/src/main/java/org/cyclonedx/gradle/utils/DependencyUtils.java#L20). In my test, calling `getName()` on the [ResolvedArtifact](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ResolvedArtifact.html) directly respected `archivesBaseName`, but the call to [ModuleVersionIdentifier's getName()](https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/12a5de0bd48b1de3946ace2fc8c1694ab3f38f58/src/main/java/org/cyclonedx/gradle/utils/DependencyUtils.java#L41) does not.

I created this example repository to reproduce the issue: https://github.com/bflood-agi/cyclonedx-gradle-plugin-issue. Happy to provide additional info if that would help.

**Comment by skhokhlov** [comment]
You can use `componentName` property now to configure name that will fully fit your project. It was added with `1.9.0` release.

Feel free to reopen the issue if it doesn't work for you.
