### ISSUE TITLE
Manual modification of Metadata

### ISSUE THREAD

**Issue by flashfishgit** [CycloneDX/cyclonedx-gradle-plugin#300]
Hi all,

is there a way to manually edit the Metadata and write the Metadata\manufacture\... Info.

The Manufacture-Metadata appears in the CycloneDx Jason Reference,
 (https://github.com/CycloneDX/cyclonedx-gradle-plugin/assets/102473074/97c65984-60dd-4ccb-95e1-9fa5ce0e67d7)
but I found no way to edit it.
![1](https://github.com/CycloneDX/cyclonedx-gradle-plugin/assets/102473074/0dbc795f-4bca-4cbb-81ff-49c4d5be37f7)

**Comment by skhokhlov** [comment]
You can follow the example in the project README https://github.com/CycloneDX/cyclonedx-core-java/issues/439. 

Feel free to reopen the issue if it doesn't work for you.
