### ISSUE TITLE
Unable to resolve POM for project dependencies which are not subprojects of the current project

### ISSUE THREAD

**Issue by loicrouchon** [CycloneDX/cyclonedx-gradle-plugin#321]
# Context

Consider the following project structure:

* `:modules:app1`
* `:modules:app2`
* `:modules:lib1`
* `:modules:lib2`

Where both `:modules:app1` and `:modules:app2` depends on `:modules:lib1` and `:modules:lib2`.
In this case as both libs should be included in both apps, it is not possible/nor desirable to make the libs subprojects of the apps.

# The Problem

Currently the cyclonedxBom task of the cyclonedx-gradle-plugin has a shortcut for subprojects not for their POM metadata to be fetched from an artifact repository as follow:

```java
resolvedConfiguration.getResolvedArtifacts().forEach(artifact -> {
    // Don't include other resources built from this Gradle project.
    final String dependencyName = DependencyUtils.getDependencyName(artifact);
    if (builtDependencies.contains(dependencyName)) {
        return;
    }
    // fetch the dependency from a repository here
}
```

and where `builtDependencies` is defined like below:

```java
final Set<String> builtDependencies = getProject()
    .getSubprojects()
    .stream()
    .map(p -> p.getGroup() + ":" + p.getName() + ":" + p.getVersion())
    .collect(Collectors.toSet());
```

This is problematic as it means that in case the local project dependencies are not sub projects of the project running the cyclonedxBom task, CycloneDX will try to fetch them from an artifact repository.
But as they haven't been published yet (part of the same Gradle build), they will never be found.

You can see that below
```
> Task :modules:app1:cyclonedxBom
CycloneDX: Parameters
------------------------------------------------------------------------
schemaVersion          : 1.4
includeLicenseText     : true
includeBomSerialNumber : true
includeConfigs         : [runtimeClasspath]
skipConfigs            : []
skipProjects           : []
destination            : <PROJECT_DIR>/build/reports/cyclonedx
outputName             : bom
------------------------------------------------------------------------
CycloneDX: Resolving Dependencies

Resource missing. [HTTP GET: https://somenexusinstance/repository/maven-group/<group/id>/lib1/1.0.0/lib1-1.0.0.pom]
Unable to resolve POM for <group.id>:lib1:1.0.0: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':modules:app1:detachedConfiguration1'.
Resource missing. [HTTP GET: https://somenexusinstance/repository/maven-group/<group/id>/lib2/1.0.0/lib2-1.0.0.pom]
Unable to resolve POM for <group.id>:lib2:1.0.0: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':modules:app1:detachedConfiguration2'.
...
```

# A potential solution (or hint towards one)

I'm not a Gradle expert, nor a CycloneDX one, but I was able to "fix" this by adding the following code at the beginning of the `for (Configuration configuration : configurations)` loop in `org.cyclonedx.gradle.CycloneDxTask#createBom`

```java
for (Dependency dependency : configuration.getAllDependencies()) {
    if (dependency instanceof ProjectDependency) {
        ProjectDependency projectDependency = (ProjectDependency) dependency;
        String dependencyId = projectDependency.getGroup() + ":" + projectDependency.getName() + ":" + projectDependency.getDependencyProject().getVersion();
        builtDependencies.add(dependencyId);
    }
}
```

This code is adding all dependencies, direct and transitive ones, which are `ProjectDependency` (i.e. gradle projects part of the same build) for each configurations to the `builtDependencies` set which otherwise only contains subprojects.

I then took a look at the generated SBOM and the one for `:modules:app1` was containing the reference to `:modules:lib1` and `:modules:lib2` and those libraries transitive dependencies were included correctly (as far as of SBOM reading capabilities).

If you agree with this analysis and the proposed fix, I can submit a PR for it.

**Comment by ChristianCiach** [comment]
@glefloch I am sorry to ask this, but is there any chance for a new release anytime soon? This PR seems to fix multiple issues for us (I tested it locally), so I am eager to see this in the next release :)

**Comment by loicrouchon** [comment]
@ChristianCiach, this was released as part of https://github.com/CycloneDX/cyclonedx-gradle-plugin/releases/tag/cyclonedx-gradle-plugin-1.8.2

Closing the issue as the fix is now released
