### ISSUE TITLE
Add dependencies of `type=zip` to dependency-graph

### ISSUE THREAD

**Issue by t-kulmburg** [CycloneDX/cyclonedx-gradle-plugin#331]
We have quite a lot of internal dependencies in our projects where we have a zip file as artifact (using `@zip` as extension in the dependencies block in build.gradle).

Using this plugin, this dependencies are correctly included in the bom file with `?type=zip`.

Also in dependency-track, they are correctly shown in the `Components` tab.

However, when using `Show in dependency graph` in dependency-track, the root of the graph is shown with `Dependency could not be found in dependency graph` displayed above.

I had a quick look through the generation of the graph in the code and found that [here](https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/master/src/main/java/org/cyclonedx/gradle/CycloneDxTask.java#L353) and [here](https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/master/src/main/java/org/cyclonedx/gradle/CycloneDxTask.java#L298) the dependencies and child dependencies are only added to the graph if the type is either `jar` or `aar`.

To get a more complete graph I would propose to also add dependencies of other types to the dependency-graph.

**Comment by skhokhlov** [comment]
done in https://github.com/CycloneDX/cyclonedx-gradle-plugin/pull/413
