### ISSUE TITLE
Metadata component is missing entries for hashes etc

### ISSUE THREAD

**Issue by danhallin** [CycloneDX/cyclonedx-gradle-plugin#340]
When generating a bom the metadata component does not get assigned the same values as entries in component list.

# Steps to reproduce

    git clone https://github.com/CycloneDX/cyclonedx-gradle-plugin.git
    cd cyclonedx-gradle-plugin
    ./gradlew cyclonedxbom
    cat build/reports/bom.json

# Expected result

metadata.component should contain entries for hashes / description / licenses / purl

# Actual result

metadata.component does not contain entries for hashes / description / licenses / purl

**Comment by skhokhlov** [comment]
1. It's not clear what exactly must be used for hash calculation for the main component. For libraries jar files are using for it, but for the project itself jar file is not a required thing. 
2. Raised a new issue to add project description: https://github.com/CycloneDX/cyclonedx-gradle-plugin/issues/472
3. You can provide licenses for your project using `licenseChoice`. Example: https://github.com/CycloneDX/cyclonedx-gradle-plugin?tab=readme-ov-file#adding-licenses-data
4. Component in metadata contains PURL. Example: 
```json
    "component" : {
      "group" : "org.cyclonedx",
      "name" : "cyclonedx-gradle-plugin",
      "version" : "1.8.2",
      "purl" : "pkg:maven/org.cyclonedx/cyclonedx-gradle-plugin@1.8.2?type=jar",
      "type" : "library",
      "bom-ref" : "pkg:maven/org.cyclonedx/cyclonedx-gradle-plugin@1.8.2?type=jar"
    }
```
