### ISSUE TITLE
Gradle configurations not being merged, resulting bom is made by a single random configuration

### ISSUE THREAD

**Issue by 37IulianPopovici** [CycloneDX/cyclonedx-gradle-plugin#367]
Hey 👋, I was testing the Gradle plugin and found that the plugin does not create an aggregate of all direct and transitive dependencies of a project. In this case, the resulting BOM reflects the dep tree of a random configuration (the last configuration that was looped). This applies also for the usage of `--init-script`

Different configurations are not merged together, the resulting BOM contains just the transitives of a single random configuration.

How to replicate:

1. Clone locally [this boilerplate](https://github.com/37IulianPopovici/gradle-configuration-merge)
2. Run `cd lib`
3. Look at bom.json, the "pkg:maven/org.apache.kafka/kafka-clients@3.0.0?type=jar" has no "dependsOn" at this moment:
![Screenshot 2023-11-20 at 16 32 33](https://github.com/CycloneDX/cyclonedx-gradle-plugin/assets/136596702/571ca9ba-2682-4e66-9b9f-163accf11556)

5. Run `gradle clean`
6. Run `gradle cyclonedxBom -info`
7. The output of bom.json might have changed, including the transitives for the "pkg:maven/org.apache.kafka/kafka-clients@3.0.0?type=jar", if not, repeat Step 5 and 6
![Screenshot 2023-11-20 at 16 38 05](https://github.com/CycloneDX/cyclonedx-gradle-plugin/assets/136596702/8dbabe00-8971-47f9-bfe3-2c5ae1f5202a)

Expecting result:
The `gradle cyclonedxBom` should produce the same output every time, an output that would merge all the dep trees resolved by all configurations (Ran `gradle dependencies -q` to get all the configs and their trees)

I am also looking to solve this issue, if you have any tips or idea that might help me, please let me know.

Gradle Version 7.6.3
Java Version 17.0.9

**Comment by skhokhlov** [comment]
I think we have 2 sources of this issue that together creating a bug:
1. Gradle provides dependencies in a random order each time
2. CycloneDX plugins is trying to avoid cycles in dependency graph and visiting dependencies only once for each configuration
