### ISSUE TITLE
Latest version 1.8.1 is not compatible with gradle 7.5.1. 

### ISSUE THREAD

**Issue by impks27** [CycloneDX/cyclonedx-gradle-plugin#374]
Latest version 1.8.1 is not compatible with gradle 7.5.1. Works for grade 8. There should be a compatibility Matrix in the documentation for this plugin.

**Comment by DevDavido** [comment]
We experienced the same issue in our project.

**Comment by newsgrep** [comment]
I have a similar problem. 

working with gradle 8.4 is: 1.7.4 1.8.0 1.8.1
working with gradle 8.5 is: 1.7.4
**NOT working with gradle 8.5 is: 1.8.0 1.8.1**

**Comment by skhokhlov** [comment]
Since it does work with gradle 8 I don't think it's going to be fixed.
