### ISSUE TITLE
Example gradle

### ISSUE THREAD

**Issue by mbayrak78** [CycloneDX/cyclonedx-gradle-plugin#4]
Hi Steve,

I followed the build.gradle at "cyclonedx-gradle-plugin/src/test/build.gradle" and was not able to run "gradlew cyclonedxBom".
After some analysis I found following workaround and could create bom.xml.
So if someone encounters same problem, this can be used.

**build.gradle:**
```
plugins {
    id 'org.cyclonedx.bom' version '1.0.0-SNAPSHOT' apply true
}

apply plugin: "java"
apply plugin: "maven"

repositories {
...
}

sourceCompatibility = 1.8
targetCompatibility = 1.8
dependencies {
	compile group: "...", name: "...", version: "..."
}

```
**settings.gradle:**
```
pluginManagement {
	resolutionStrategy {
		eachPlugin {			
			if (requested.id.toString() == 'org.cyclonedx.bom') {
				useModule('org.cyclonedx:cyclonedx-gradle-plugin:1.0.0-SNAPSHOT')
			}
		}
	}
	repositories {
		maven {
			url 'https://oss.sonatype.org/content/repositories/snapshots'
		}
		maven {
			url '...'
			credentials {
				username "..."
				password "..."
			}
		}
	}
}

```
Important: only gradle versions 4.10+ supports plugins from snapshot repo.

**Comment by stevespringett** [comment]
This is fantastic. Folks (myself included) have been blocked by our inability to test the development of the plugin. See #1 . So this info will be really helpful in getting the plugin development moving along and eventually released.

**Comment by mbayrak78** [comment]
I am glad to support this plugin development.
Looking forward to see it released :)

**Comment by stevespringett** [comment]
This gave me the jumpstart I needed to finish. Plugin is being released now.
