### ISSUE TITLE
XmlPullParserException when using with io.gatling.gradle:3.11.2 plugin  

### ISSUE THREAD

**Issue by SpanVagyTeso** [CycloneDX/cyclonedx-gradle-plugin#435]
When i try to run cyclonedXBom with the following build.gradle.kts configuration i'll get XmlPullParserException.
```kotlin
plugins {
    kotlin("jvm") version "1.9.23"
    id("java")
    id("io.gatling.gradle") version "3.11.2"
    id("org.cyclonedx.bom") version "1.8.2"
}

group = "help"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(21)
}
```

**Comment by SpanVagyTeso** [comment]
Meanwhile I found the exact issue.

Gatling plugin uses newer plexus utils
`org.codehaus.plexus:plexus-utils:3.4.1 -> 4.0.1`

**Comment by skhokhlov** [comment]
Unfortunately, we cannot upgrade version of plexus because it's a dependency of maven core (https://github.com/apache/maven/blob/maven-3.9.8/pom.xml#L139). I see that maven uses newer version in the beta versions of maven 4.x.x, so I expect they will be upgraded together.
