### ISSUE TITLE
cyclonedx plugin download is failing.

### ISSUE THREAD

**Issue by iamrakesh-kumar** [CycloneDX/cyclonedx-gradle-plugin#456]
15:37:09  FAILURE: Build failed with an exception.
15:37:09  
15:37:09  * What went wrong:
15:37:09  A problem occurred configuring project ':app'.
15:37:09  > Could not resolve all files for configuration ':app:classpath'.
15:37:09     > Could not resolve org.cyclonedx:cyclonedx-gradle-plugin:1.6.1.
15:37:09       Required by:
15:37:09           project :app > org.cyclonedx.bom:org.cyclonedx.bom.gradle.plugin:1.6.1
15:37:09        > Could not resolve org.cyclonedx:cyclonedx-gradle-plugin:1.6.1.
15:37:09           > Could not get resource 'https://plugins.gradle.org/m2/org/cyclonedx/cyclonedx-gradle-plugin/1.6.1/cyclonedx-gradle-plugin-1.6.1.pom'.
15:37:09              > Could not GET 'https://plugins-artifacts.gradle.org/org.cyclonedx/cyclonedx-gradle-plugin/1.6.1/6e3ffd026be2b8d51ca69d04cc72e3738b6760f904463dbe28d871e14dd8b60c/cyclonedx-gradle-plugin-1.6.1.pom'.
15:37:09                 > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
15:37:09  

https://plugins.gradle.org/m2/org/cyclonedx/bom/org.cyclonedx.bom.gradle.plugin/1.6.1/org.cyclonedx.bom.gradle.plugin-1.6.1.jar   -- Not found.
pom files are downloading

 https://plugins.gradle.org/m2/org/cyclonedx/cyclonedx-gradle-plugin/1.6.1/  -- URL should be pointed to this???

**Comment by iamrakesh-kumar** [comment]
https://plugins.gradle.org/m2/org/cyclonedx/cyclonedx-gradle-plugin/1.6.1/   -- pointing to this will not solve issue.
ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.

**Comment by skhokhlov** [comment]
This exception is thrown by the underlying JVM, not CycloneDX plugin or Gradle. It can be related to your network environment (like proxy, VPN). You can see here how to debug your SSL connection: https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/ReadDebug.html

**Comment by iamrakesh-kumar** [comment]
yes, Got resolved thanks.
