### ISSUE TITLE
Add external git reference to metadata.component.externalreferences

### ISSUE THREAD

**Issue by barblin** [CycloneDX/cyclonedx-gradle-plugin#519]
**Is your feature request related to a problem? Please describe.**
To be able to use sboms at scale, we would need a reference to the git repository in metadata.components as well. In the current implementation, that is not possible.

**Describe the solution you'd like**
I've create a local branch where I have a suggestion implementation and test. It would be great if I could create a PR, as of now I receive an 403.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by jeremylong-snc** [comment]
@skhokhlov - should this be considered closed via #520?

**Comment by barblin** [comment]
from my side definitely ;)
