### ISSUE TITLE
Vulnerabilities in the SBOM file

### ISSUE THREAD

**Issue by Cristina-Melinda** [CycloneDX/cyclonedx-gradle-plugin#551]
I need to see the vulnerabilities on any of the components listed in the SBOM files.
I'm using CycloneDX Gradle Plugin, version 1.8.2, but there is no vulnerabilities array present in the generated SBOM file.

Ideally, when the SBOM files are generated, would be nice that the files would contain the vulnerabilities as well. 

Is there any way to get the vulnerabilities automatically in a Android Gradle project, based on SBOM, or an additional gradle plugin?

**Comment by skhokhlov** [comment]
Vulnerability analysis is out of scope for CycloneDX plugins. You can use [OWASP dependency-check ](https://github.com/jeremylong/DependencyCheck) or [Dependency-Track](https://github.com/DependencyTrack/dependency-track).
