### ISSUE TITLE
Gradle fails: plugin org.cyclonedx.bom not found

### ISSUE THREAD

**Issue by rasguanabana** [CycloneDX/cyclonedx-gradle-plugin#6]
Hi,

I wanted to try this plugin in a sample project. I changed `build.gradle` in following manner:
```diff
diff --git a/build.gradle b/build.gradle
index 59746ca..dab9488 100644
--- a/build.gradle
+++ b/build.gradle
@@ -3,7 +3,10 @@ plugins {
     id 'groovy'                           //for mixed java/groovy project
     id 'war'                                //for genarating war files
     id 'org.akhikhl.gretty' version '2.0.0' //web app development plugin
+    id 'org.cyclonedx.bom' version '1.0.0' apply true
 }
+apply plugin: 'java'
+apply plugin: 'maven'
 
 sourceCompatibility = "1.8"
 targetCompatibility = "1.8"
@@ -16,7 +19,7 @@ task wrapper(type: Wrapper) {
 }
 
 repositories {
-    mavenCentral()
+    mavenCentral() //already there
     maven {
         url "http://maven.restlet.org/"
     }
```

It fails however with following error:

```
$ sh gradlew cyclonedxBom

FAILURE: Build failed with an exception.

* Where:
* Build file '/home/*****/repos/_external/softeng17b/build.gradle' line: 6
*
* * What went wrong:
* Plugin [id: 'org.cyclonedx.bom', version: '1.0.0'] was not found in any of the following sources:
*
* - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
* - Gradle Central Plugin Repository (no 'org.cyclonedx.bom' plugin available - see https://plugins.gradle.org for available plugins)
*
* * Try:
* Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
*
* * Get more help at https://help.gradle.org
*
* BUILD FAILED in 1s
*
```

Could you help to check? Thanks.

**Comment by stevespringett** [comment]
Gradle is unable to resolve the plugin. Refer to https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/master/src/test/settings.gradle

I'll add this to the readme.

**Comment by rasguanabana** [comment]
Adding `settings.gradle` as stated in readme and upgrading Gradle version helped. Thanks!

**Comment by stefanneuhaus** [comment]
The initial try with the `plugins { }` DSL block did not work as is always tries to retrieve the plugin from the [Gradle Plugin Portal](https://plugins.gradle.org/).

Using the [_traditional way_](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:using_your_plugin_in_another_project) of applying plugins it is also possible to retrieve plugins from other repositories like Maven Central.

**Comment by stevespringett** [comment]
Closing

**Comment by matteoturra** [comment]
Sono fuori dall'ufficio fino a 09/09/2019




Nota: Questa è una risposta automatizzata al messaggio  "Re:
[CycloneDX/cyclonedx-gradle-plugin] Gradle fails: plugin org.cyclonedx.bom
not found (#6)" inviata il 03/09/2019 03:57:30.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.
