### ISSUE TITLE
How to change the generated BOM location for gradle plugin

### ISSUE THREAD

**Issue by jayragshukla** [CycloneDX/cyclonedx-gradle-plugin#62]
I want to generate into ./build/reports/cyclondx/bom.xml. Is it possible in gradle plugin? Thanks

**Comment by stevespringett** [comment]
Not currently possible. Location is hard coded.

https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/master/src/main/java/org/cyclonedx/gradle/CycloneDxTask.java#L275

However, pull requests are accepted.

**Comment by Ishaq-AppDirect** [comment]
Anyone reading this the report is saved in the reports directory of your project

https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/master/src/main/java/org/cyclonedx/gradle/CycloneDxTask.java#L378
