### ISSUE TITLE
includeConfigs as alternative to skipConfigs

### ISSUE THREAD

**Issue by msymons** [CycloneDX/cyclonedx-gradle-plugin#68]
You can control the configurations included in the BOM using `skipConfigs`.

As an enhancement, it would be useful to be able to alternately explicitly specify includes using (say) `includeConfigs`.  The intention is to allow the user to say what they want rather than what they do not want.

Currently, my plugin v1.3 setup has to specify 13 configs to skip:
```
cyclonedxBom {
    // Exclude test classpaths from BOM
    skipConfigs +=
            ["aClasspath",
             "anotherClasspath",
             "yetAnotherClasspath",
             "omg",
             "this",
             "is",
             "getting",
             "really",
             "tedious",
             "darnit",
             "still",
             "not",
             "finished"]
```

**Comment by Loffe** [comment]
Good idea, this would be helpful to me as well :)

**Comment by Horsed** [comment]
Opened https://github.com/CycloneDX/cyclonedx-gradle-plugin/pull/90 for an allow list
