### ISSUE TITLE
lots of errors when running, tho does produce bom.xml

### ISSUE THREAD

**Issue by llamahunter** [CycloneDX/cyclonedx-gradle-plugin#7]
It produces about 20 lines like

Unable to resolve POM for org.cyclonedx.model.Component@f15cdcaf: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':detachedConfiguration124'.

But does produce a bom.xml.  From the above message, it's unclear what it's having trouble with.  What is 'detachedConfigurationNNN'?

**Comment by llamahunter** [comment]
FWIW, I enabled 'gradle --debug' and looked at the stuff around this error message.  It's for a jar that is missing a pom.  It would be better if the error message mentioned the jar name, tho, rather than 'detatchedConfiguration'.

**Comment by sschuberth** [comment]
This issue seem to be duplicated by https://github.com/CycloneDX/cyclonedx-gradle-plugin/issues/13, which actually was fixed in https://github.com/CycloneDX/cyclonedx-gradle-plugin/pull/11, but there's no release with that fix yet.

@stevespringett, can we please get a release with that fix included?

**Comment by matteoturra** [comment]
Sono fuori dall'ufficio fino a 09/09/2019




Nota: Questa è una risposta automatizzata al messaggio  "Re:
[CycloneDX/cyclonedx-gradle-plugin] lots of errors when running, tho does
produce bom.xml (#7)" inviata il 02/09/2019 18:10:26.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by stevespringett** [comment]
v1.1.1 was released to Maven Central which includes #11. Closing issue. If the reported problem persists, feel free to reopen

**Comment by matteoturra** [comment]
Sono fuori dall'ufficio fino a 09/09/2019




Nota: Questa è una risposta automatizzata al messaggio  "Re:
[CycloneDX/cyclonedx-gradle-plugin] lots of errors when running, tho does
produce bom.xml (#7)" inviata il 03/09/2019 03:56:03.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by tdillan** [comment]
I'm also seeing the behavior described by this issue, even after upgrading to version 1.1.1 of the plugin.

I have a multi-project gradle build with the cyclonedx plugin applied to the root project.
When I run `./gradlew cyclonedxBom`, I get thousands of messages of the format:
```
Unable to resolve POM for org.cyclonedx.model.Component@2e6083f7: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':detachedConfiguration3145'.
```

**Comment by sschuberth** [comment]
Out of curiosity @tdillan, which version of Gradle / the wrapper are you using?

**Comment by tdillan** [comment]
@sschuberth I'm using Gradle 5.5.

It's worth noting that despite the many error messages, the plugin _does_ produce a BOM and it appears to have the expected content, but in my case produces over 700K worth of log output in the process.

**Comment by llamahunter** [comment]
See my comments above. Something in your dependency chain is very likely missing its .pom file, which means that the bom is likely incomplete.  I agree it would be nice if the error messages were not ungodly verbose, but rather brusque and pointed. ;-)

**Comment by tdillan** [comment]
Interestingly, I don't get any of the errors mentioned if I run the cyclonedxBom task on the sub-projects individually.  They only occur on when the task is run from the root project, which itself does not have any dependencies declared.  It's just an umbrella project with sub-modules.
