### ISSUE TITLE
Android - skipConfigs & projectType configuration not working

### ISSUE THREAD

**Issue by Didier116** [CycloneDX/cyclonedx-gradle-plugin#82]
Usage on README.md specify : 
_Configuration: You can control the configurations included in the BOM:_

```
cyclonedxBom {
    // skipConfigs is a list of configuration names to exclude when generating the BOM
    skipConfigs += ["compileClasspath", "testCompileClasspath"]
    // Specified the type of project being built. Defaults to 'library' 
    projectType = "application"
    // Specified the version of the CycloneDX specification to use. Defaults to 1.2.
    schemaVersion = "1.2"
}
```

I use the "skipConfigs" property to exclude some tests configuration which are in error but execution continue failing using the excluded configuration.

Moreover, "projectType" can't be set because this property is private and there is no setter allowed.

Has anyone had the same problem and could help

**Comment by Jaff** [comment]
Yes, I have also observed this behavior. Reported also in cyclonedx.slack.com in #java-gradle channel.

**Comment by davidcre** [comment]
Observing the same result in an Android project.
I hope it's related to the variants not resolving properly on library projects when being declared from the root of the project.

**Comment by hrishabhjain** [comment]
I am also observing the same behaviour.

**Comment by nicopico-dev** [comment]
Adding `projectType=application` in `gradle.properties` seems to do the trick for projectType

**Comment by ChristianCiach** [comment]
Editing the `gradle.properties` is not always a solution.

If you have multiple gradle subprojects and some of them are libraries and some of them are applications, then there is currently no way to configure different cyclonedx-tasks accordingly. This is a real bug that needs fixing. The fix seems to be trivial, so I will probably submit a PR eventually if nobody beats me to it.

**Comment by ChristianCiach** [comment]
Actually, this has already been fixed by @glefloch : https://github.com/CycloneDX/cyclonedx-gradle-plugin/commit/7d70c120febf9a542d4b355e4592cbc4c068af5d :tada:

I think this issue can be closed.

**Comment by glefloch** [comment]
Great thanks, I'm closing this.
