### ISSUE TITLE
Is it possible to define inputs and outputs for the Gradle Task so that the BOM is only newly created when the dependencies have changed?

### ISSUE THREAD

**Issue by gebhardt** [CycloneDX/cyclonedx-gradle-plugin#95]
Generating the BOM takes a while, and it would be really nice, if it is only generated, if the dependencies have changed.
If they are unchanged, the result should be taken from the BOM.

**Comment by stevespringett** [comment]
I'm not sure it would help performance that much. The hashes of all components would still need to be generated as the jars residing in .m2 and .gradle could change (maliciously, corruption, etc) without the stated dependencies in gradle changing. There's also network considerations. If resolving from a repo, there's usually no guarantee that a build system will retrieve the same dependency from the same mirror. In the event one mirror gets compromised and others do not, relying solely on previous hash values would lead to a false sense of security.

I'm open to proposals that would not have an adverse impact on security.
